### ISSUE TITLE
Missing v0.4 SMD symbols after importing in KiCAD 8

### ISSUE THREAD

**Issue by Thrathra** [Alarm-Siren/arduino-kicad-library#105]
Hi, I'm currently working on the v0.4.4d SMD project.

It seems that some symbols are lacking after importing the project.
For instance, a diode is missing at the right of the power regulator page 4, and the circuit at the right of the S1 component is missing aswell on the same page.
Do I have to install additional libraries and if so, which ones?
Furthermore, it is not clear if I have to use the "v0.4.4d.kicad_pro" file or the "v0.4.4d.pro" as they have different sizes.

Thanks in advance!

**Comment by Alarm-Siren** [comment]
Hi @Thrathra,

I think you might have confused this repo for another one, this is just a library of arduino footprints and symbols. There are no 'projects' to be imported, no multipage circuits, and there's certainly no such file as "v0.4.4d.kicad_pro" or "v0.4.4d.pro" anywhere in this repo.

**Comment by Thrathra** [comment]
Oh I'm really sorry, I posted on the wrong repo indeed.
