### ISSUE TITLE
New Board: Arduino MKR Zero

### ISSUE THREAD

**Issue by Alarm-Siren** [Alarm-Siren/arduino-kicad-library#13]

**Comment by Alarm-Siren** [comment]
Having difficulty obtaining good mechanical drawings for this part. If anyone can help, that'd be grand.

**Comment by Alarm-Siren** [comment]
Let's face it, I'm never going to actually get around to doing this...

**Comment by Chamsta123** [comment]
G'day, Alarm-Siren. What is it you were after? Was it the PCB for the MKR Zero, or just the footprint? I'm about to embark on a journey which will end up with me making at least the footprint, so I wondered if that would be of any help to you?

**Comment by Alarm-Siren** [comment]
Just the footprint. I've never actually seen a MKR, nor had reason to buy one, and getting mechanical drawings - i.e. where the edges and pins are located - proved illusive.

I've not had time to review it yet, but someone submitted a pull request #27 a MKR of some kind...
