### ISSUE TITLE
Update the library to reflect the new Kicad Library Convention

### ISSUE THREAD

**Issue by Alarm-Siren** [Alarm-Siren/arduino-kicad-library#26]
http://kicad-pcb.org/libraries/klc/

**Comment by pintert3** [comment]
Anything on this?
Is there anything in particular we need to edit in the library for it to be ported to the new format?
Also the link is old. Which brings me to the question, is this library still in maintenance?

**Comment by Alarm-Siren** [comment]
Hello! Yes, I am still around and (one day) I do intend to come back to do things. However, if you want to help out I am more than open to anyone who wishes to contribute.

You're quite right the link is out of date, here is the new one: https://klc.kicad.org/

I don't know if there's anything specific that needs to be done to bring it into compliance with KLC - its been so long since I last looked at it, and no doubt the conventions have changed in the interim anyway. Its just a matter of going through the document at the link and making either ticking off if its right, or fixing it if it isn't.

**Comment by Alarm-Siren** [comment]
Decided I have no interest in doing this. I am happy with my library's internal conventions. The KLC are only relevant if someone wants to add it to Kicad's standard library, in which case they are free to do the work!
