### ISSUE TITLE
Pro Mini Clone

### ISSUE THREAD

**Issue by fow0ryl** [Alarm-Siren/arduino-kicad-library#28]
Since there are many Pro Mini Clones on ebay (and I have more then 10 of them) it would be nice to support it here.
All of my board's are about 33x18mm in size
![Pro_Mini_Clone](https://user-images.githubusercontent.com/5961849/54122147-8c872f00-43fc-11e9-9a6a-4defbc006b44.jpg)

**Comment by Alarm-Siren** [comment]
Please see #23 for continuation of this topic.
