### ISSUE TITLE
New Board: Arduino MKR NB 1500

### ISSUE THREAD

**Issue by Alarm-Siren** [Alarm-Siren/arduino-kicad-library#37]

**Comment by Alarm-Siren** [comment]
Pinout and mechanical dimensions are identical to the MKR FOX 1200.

**Comment by G0rocks** [comment]
Hello, I'm using this board for a project and I note that it does not have the following:

- [ ] SIM card slot
- [ ] Antenna connector
- [ ] USB micro connector
- [ ] Battery connector
- [ ] UART (I think it's a uart, I'm not so sure)

How can I add these to the board in this library?

I found these by looking at this page:
https://store.arduino.cc/en-nl/products/arduino-mkr-nb-1500?srsltid=AfmBOoq0kSyw09yKAP7OWHopdxzi9nz71oJWrUyyui7OEPT0WYp6BbZd

Thank you :)

**Comment by Alarm-Siren** [comment]
Hi @G0rocks 

I think you may be confused about what these symbols and footprints are for. They are not re-implementations of the actual Arduino modules themselves, rather they are footprints to allow you to plug an Arduino module into your own custom PCB. Given this fact there is no reason why any of the components you listed above would be included in the library, as they do not affect the outline of the footprint (well, except for the USB micro, which is actually present in the footprint insofar as it affects the outline).

**Comment by G0rocks** [comment]
Hello
Thanks for the response.
Yes I read the description of the repo to be
"KiCad Symbol & Footprint Library for Arduino Modules (Shields, Sockets and Tiles) " which I understood as that they would be the actual arduino module themselves.
Now I'm curious though since you say these "... are not re-implementations...", does that mean that somewhere online I could find an arduino module for kicad which would include the things I pointed out? If so, where do I find that module? Thank you!

**Comment by Alarm-Siren** [comment]
@G0rocks 
I'm not aware of any examples of re-implementations of the Arduino Modules themselves in native Kicad format (though they may well exist, I have never seen them). However, you can download the original Eagle files for most of the Arduino modules, for example the MKR NB 1500 can be found at (https://content.arduino.cc/assets/MKRNB1500-reference.zip). You can then import the eagle files directly into Kicad via File -> Import -> Eagle Project. Note, however, this process is not perfect and you will lose some data along the way so you will likely need to tidy it up after import if you plan to use it for anything more than just reference.

**Comment by G0rocks** [comment]
Thank you!
Would it be an idea to add the boards to this library as a board, not a socket?
This is what I get from the eagle file

![Image](https://github.com/user-attachments/assets/56cc7414-33d5-4642-8d47-510e6a38cb75)

It is not really useful for what I'm thinking. I just wanted to plop a box with all the connectors on it for the arduino mkr nb 1500 in a schematic so I could connect it to other things.
