### ISSUE TITLE
New Boards

### ISSUE THREAD

**Issue by Alarm-Siren** [Alarm-Siren/arduino-kicad-library#4]
Add parts for the Arduino Nano & Mini as Sockets. Need to investigate these parts, find physical dimensions and pinouts etc.

**Comment by vikramambrose** [comment]
When using a shield, how does one align the pin headers in the 3dviewer to be exactly over the holes from the arduino footprint?

**Comment by Alarm-Siren** [comment]
I'm sorry, but I do not know the answer to your question for certain as I have never used the 3D viewer myself.
If you have a shield footprint in your PCB design, along with my footprint (which presumably you do in order to get both to show up in the 3D viewer), you can make fine adjustments to the position of one or both by hovering over the component and pressing 'E' to bring up the Footprint Properties dialogue, and adjusting the position X/Y in the bottom left corner of the dialogue.
If you just want to check alignment of pins, I've always found it simplest to print the circuit on a piece of paper and physically place the components on the printout.
Further, just for future reference, you should have created a new issue rather than commenting on this unrelated one.

**Comment by Alarm-Siren** [comment]
See #6 and #7 .
