### ISSUE TITLE
In the Pro_Mini_Clone_Socket symbol, MISO and MOSI are backwards

### ISSUE THREAD

**Issue by DeflateAwning** [Alarm-Siren/arduino-kicad-library#84]
Currently, the GPIO pins in the Pro_Mini_Clone_Socket are:
* D11_MISO
* D12_MOSI

Current picture:
![image](https://user-images.githubusercontent.com/11021263/229992081-5d609db2-1411-4993-b7af-c970cc44704c.png)

It should be the opposite:
* D11_MOSI
* D12_MISO

Someone should check that these are correct in the other schematic symbols too! Big big mistake.

**Comment by Alarm-Siren** [comment]
Thank you for the bug report, you are indeed correct.
I have checked all the symbols for incorrect MISO/MOSI assignment and only the Arduino Pro Mini and Clone Pro Mini are affected.

**Comment by Alarm-Siren** [comment]
Version 4.0.1 addresses this issue, and I have submitted it to KiCad for inclusion in the PCM (see merge request here: https://gitlab.com/kicad/addons/metadata/-/merge_requests/203). Unfortunately I have no control over how long it will take the KiCad team to review and approve the new release - last time it took six days.

In the mean time you can manually install the updated library using the PCM package file here: https://github.com/Alarm-Siren/arduino-kicad-library/releases/tag/v4.0.1

**Comment by DeflateAwning** [comment]
Thank you for fixing this so quickly
