### ISSUE TITLE
mkr 1300 - pins orders

### ISSUE THREAD

**Issue by crepseS** [Alarm-Siren/arduino-kicad-library#89]
Hi  in the official documentation  https://docs.arduino.cc/static/56e4f5bef7037ff6d3e450cdfd327de1/ABX00017-full-pinout.pdf  

pins order is not the same as in this library therefore it can not be plugged to an actual arduino mkr 1300 board.

**Comment by Alarm-Siren** [comment]
I have reviewed the MKR 1300 symbol and the MKR 1200 footprint (which is re-used for the MKR 1300 symbol), and I can confirm that the pinout exactly matches the one given in the document you have linked to (see below).

Are you able to be more specific what problem you are having?

_(side note: all the MKR boards have the same pinout, so if this one really is wrong then they're all wrong.)_

![mkr1300](https://github.com/Alarm-Siren/arduino-kicad-library/assets/21121685/3f5a9ab6-e000-4be8-a075-383d44d3a151)

**Comment by crepseS** [comment]
the problem seems solved when i migrated the lib to kickad 7

**Comment by crepseS** [comment]
see the image 
<img width="449" alt="Capture" src="https://github.com/Alarm-Siren/arduino-kicad-library/assets/41874833/6e687e35-c48b-449f-a389-037b702b5fa6">

**Comment by crepseS** [comment]
Now I understand , on pcb  the pins are ok but on schematic they look not in the same position .   I guess this should not be a problem.

**Comment by Alarm-Siren** [comment]
The location of the pins on the symbol have no relation to the physical locations of the pin on the module. This is normal for all schematic components in Kicad.

By convention, "inputs" are on the left of the symbol, "outputs" are on the right, power in on the top and ground connections are on the bottom (note the present version of this library does not fully follow this convention, but my point is its totally normal for the two to be unrelated)
